### ISSUE TITLE
Solve forward problem doesn't work

### ISSUE THREAD

**Issue by Ryanzzzjw** [DavidMetzIMT/App_EIDORS_ModelSim#4]
1. "Solve Forward" doesn't work and cause error which is shown in the screenshot.

![image](https://user-images.githubusercontent.com/56712664/171010147-300fe7e3-050b-483c-b0e7-ad5ebbb72e36.png)
![image](https://user-images.githubusercontent.com/56712664/171009689-ef98274e-01fb-42d4-a471-65b2fce85a13.png)

2. And in EIT_sim_env, "data_hn" and "data_ihn" is missing in properties, generating AI dataset works when add them.

![image](https://user-images.githubusercontent.com/56712664/171011576-36541de0-be6a-4379-8f32-ee0bdcc8e327.png)

**Comment by DavidMetzIMT** [comment]
see commit
